### PR TITLE
More blocks

### PR DESCRIPTION
**Pull request by elthariel**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/elthariel/blocks/pull/6" target="_blank">ReviewNinja

**Comment by Champii** [comment]
:+1:

**Comment by elthariel** [comment]
Hum .... Broken standard library ?

Honestly, I don't know. I'll bring my VM up to check this up

**Comment by Champii** [comment]
Every error seems to be related to the 'epsilon()' call and its library. Is it from the stdlib ?!

**Comment by elthariel** [comment]
Yup

**Pull request merged**
